### ISSUE TITLE
Use org.schema.Person to facilitate a 'contact lookup' from a given repository

### ISSUE THREAD

**Issue by whistlinjoe** [Eduworks/ec#13]
Use org.schema.Person (or equivalent) to facilitate a 'contact lookup' from a given repository

**Comment by Lomilar** [comment]
Note: Given the ability for anyone to create their own name (and therefore label) as a contact lookup, this makes spoofing incredibly easy. This should be combined with some sort of domain/key/email proof of name/proof of domain.

I am not entirely sure how to approach this at the moment. CEDAR has one method.

**Comment by Lomilar** [comment]
We now do a contact lookup from the public key. This still doesn't solve the spoofed identity problem, but we can at least prove that the owner of this public key claims to have these attributes (name, email, phone). Going the other way is still dangerous.
