### ISSUE TITLE
Time sync can drift out of sync, breaking communication.

### ISSUE THREAD

**Issue by Lomilar** [Eduworks/ec#15]
Upon EcRepository ping, should calculate server time offset to ensure requests fall within the 60 second window.

**Comment by stuartasutton** [comment]
This is happening to me...certainly no 60 second time lapse

**Comment by Lomilar** [comment]
This issue is not entirely resolved. Auto detection of a repo seems to do this, but setting the server by hand doesn't do the ping / time sync. See if this is the issue.

**Comment by cwd-mparsons** [comment]
@Lomilar We are encountering this issue on the test server (two people) now!

**Comment by Lomilar** [comment]
The server time has been re-synchronized to internet time. Should be fixed for ya.

**Comment by cwd-mparsons** [comment]
thanks
