### ISSUE TITLE
Alter the addFramework method in EcFrameworkGraph to use EcCompetency.search and EcAlignment.search instead of EcRepository.multiget

### ISSUE THREAD

**Issue by whistlinjoe** [Eduworks/ec#38]
Currently EcFrameworkGraph takes a big performance hit using EcRepository.multiget in the addFramework method. 

Using CAP Database Systems (https://sandbox.cassproject.org/api/custom/data/schema.cassproject.org.0.3.Framework/fd992893-1d5a-432f-ba24-d88d20d44f50) as a test case, EcFrameworkGraph.addFramework took over 20 seconds to process.  Almost the entire duration of the test case was spent in the EcRepository.multiget method.

**Comment by whistlinjoe** [comment]
Replacing multiget improved performance from over 20 seconds to just over 2.5 seconds.

**Comment by Lomilar** [comment]
My understanding of the performance of multiget doesn't reflect the evidence here exactly.

Precache is decidedly quick, are there a ton of gets afterwards that are causing the slowdown?

**Comment by Lomilar** [comment]
Was EcRepository.caching turned on for these tests?

**Comment by whistlinjoe** [comment]
No.  That appears to be the problem.   

This works wonderfully:
var repo = new EcRepository();
EcRepository.caching = true;

This not so much:
var repo = new EcRepository();
repo.caching = true;

Do you want me to switch back to the multiget?  It is still in the file (commented out).

**Comment by Lomilar** [comment]
I have it restored and waiting for commit.

Nonetheless, we should keep this open because no caching is a legitimate configuration option... and we should decide what to do in a default case. (default caching to on?)

**Comment by whistlinjoe** [comment]
Can we just check to see if caching is enabled?

The addFramework could just check and if it is enabled do multiget, if not do search?

**Comment by Lomilar** [comment]
Search doesn't encompass the entirety of possibility for finding a resource, I don't think. I'd like to avoid crossing or confusing the behavior of get and search.

This can probably be fixed by having precache call success with the things it was able to successfully get, and then multiget can reattempt to get things that didn't come back from precache.

**Comment by Lomilar** [comment]
60526c948a4247d9287008582a312c99a3a69467 - Reverted. Closing.
