### ISSUE TITLE
Consider whether copyFrom should remove fields that show up in the object template.

### ISSUE THREAD

**Issue by Lomilar** [Eduworks/ec#59]
See ceasn:inLanguage
https://github.com/cassproject/cass-editor/issues/548

Arguably, a default field in a template should be used instead of nothing when copyFrom is invoked.

Requires discussion/impact assessment.

**Comment by Lomilar** [comment]
If done, remove the inLanguage check from CASE import.

**Comment by woodkri** [comment]
Resurfacing this. Who needs to be involved in this discussion, you, me and Tom?

**Comment by Lomilar** [comment]
Sure. @whistlinjoe

One item to consider is whether default fields violate implicit "data purity" rules of an import -- that an import may not have some information on purpose, and by adding default fields, you could be setting those data to something incorrect. (as in an import from Estonia or the UK)

Another item to consider is that a direct copy of an object copies over signatures. Those signatures will be made invalid by the introduction of new fields by the destination, presumably before the `.verify()` method is run.

One mitigation could be that if the signature field is present in the object being copied (it is a legitimate CaSS object that is being copied from) then we don't copy data from the template over to the object, otherwise we do.

**Comment by woodkri** [comment]
That would satisfy the issue with regards to the CTDL-ASN CSV import since there are no signatures in that format.

**Comment by Lomilar** [comment]
Yeah, but it introduces unseen complexity. For instance, importing a framework from another CaSS instance -- this wouldn't work.

That makes it far from my favorite, but would suffice for the CE use case -- the only place where templates are used, if I recall.

**Comment by woodkri** [comment]
Right I thought about that too, but importing from another CaSS instance I'm going to have to handle ownership after the copyFrom operation anyway I think, similarly to how we copy competencies from one framework to another. I'll just make sure to check the template then.

I guess I could just do that for the CSV import too, check the template and add owner after the copyFrom.

**Comment by Lomilar** [comment]
I suppose, a CaSS-CaSS framework import where it strips/replaces the permissions is probably something that some folks will want.

**Comment by woodkri** [comment]
If it's only CE using templates and just the owner field that's an issue right now, it probably makes more sense for me to just check the template and add any owners as part of the import process. I'm going to move forward with that unless anyone has any objections, and would be fine with closing out this issue. I have the CSV template issue captured in another ticket.

**Comment by Lomilar** [comment]
OK, I'm agreed that there's no uniform way to approach this.
